In [1]:
import torch as th

In [2]:
empty = th.empty(3, 3)
empty

tensor([[ 1.5891e-42,  0.0000e+00, -3.8816e-37],
        [ 3.0873e-41,  1.6816e-44,  0.0000e+00],
        [-3.8815e-37,  3.0873e-41,  1.5905e-42]])

In [3]:
ones = th.ones(3, 3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [6]:
diag = th.diag(th.tensor([1, 1, 1]))
diag

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

In [8]:
scalar = th.tensor(1)
scalar

tensor(1)

In [9]:
vector = th.tensor([1, 1, 1])
vector

tensor([1, 1, 1])

In [10]:
matrix = th.tensor([[1, 1, 1], [1, 1, 1], [1, 1, 1]])
matrix

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [12]:
d3_tensor = th.tensor([[[1, 1, 1], [1, 1, 1], [1, 1, 1]], [[1, 1, 1], [1, 1, 1], [1, 1, 1]], [[1, 1, 1], [1, 1, 1], [1, 1, 1]]])
d3_tensor

tensor([[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]])